# Generated by Django 5.2 on 2025-04-19 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft_living', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('grade', models.IntegerField()),
                ('floors', models.FloatField()),
                ('sqft_lot', models.FloatField()),
                ('house_age', models.IntegerField()),
                ('sqft_living15', models.FloatField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('predicted_price_min', models.FloatField()),
                ('predicted_price_max', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
